name: Build and Test

on: # trigger
  push: # event
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build_and_test: # job (sequence of 'steps')
    name: Build & Test on Ubuntu with GCC
    runs-on: ubuntu-latest

    steps:
      # Step 1 : Clone the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2 : Toolchain setup
      - name: Set up C++ toolchain (Clang)
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      # Step 3 : Configure project with CMake
      - name: Configure CMake
        run: |
          CXX=clang++ cmake -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_STANDARD=20

      # Step 4 : Build project
      - name: Build
        # -j$(nproc) starts execution of building in parallel with available count of cpu cores
        run: cmake --build ${{github.workspace}}/build -j$(nproc)

      # Step 5 : Run Ctest
      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure
